/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/Transactions/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        file?: components["schemas"]["IFormFile"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Response"];
                        "application/json": components["schemas"]["Response"];
                        "text/json": components["schemas"]["Response"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    startDate?: string;
                    endDate?: string;
                    iban?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TransactionResponseModel"][];
                        "application/json": components["schemas"]["TransactionResponseModel"][];
                        "text/json": components["schemas"]["TransactionResponseModel"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Transactions/ibans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string[];
                        "application/json": string[];
                        "text/json": string[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Transactions/cashflow-per-iban": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    startDate?: string;
                    endDate?: string;
                    iban?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CashflowDto"];
                        "application/json": components["schemas"]["CashflowDto"];
                        "text/json": components["schemas"]["CashflowDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/TransactionsFileJob/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TransactionsFileJobResponseModel"];
                        "application/json": components["schemas"]["TransactionsFileJobResponseModel"];
                        "text/json": components["schemas"]["TransactionsFileJobResponseModel"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BalanceAtDateDto: {
            /** Format: date */
            date?: string;
            /** Format: decimal */
            balance?: number;
        };
        CashflowDto: {
            iban: string;
            balancesPerDate: components["schemas"]["BalanceAtDateDto"][];
        };
        /** Format: binary */
        IFormFile: string;
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        };
        Response: {
            /** Format: uuid */
            jobId?: string;
        };
        TransactionResponseModel: {
            /** Format: int32 */
            id?: number;
            /** Format: int32 */
            followNumber?: number;
            iban: string;
            /** Format: decimal */
            amount?: number;
            /** Format: date */
            dateTransaction?: string;
            nameOtherParty?: string | null;
            ibanOtherParty?: string | null;
            authorizationCode?: string | null;
            description?: string | null;
            /** Format: date */
            cashbackForDate?: string | null;
        };
        TransactionsFileJobResponseModel: {
            /** Format: uuid */
            id?: string;
            originalFileName?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            processedAt?: string | null;
            status?: string | null;
            errorMessage?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
