-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
	"MigrationId" varchar(150) PRIMARY KEY NOT NULL,
	"ProductVersion" varchar(32) NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "transactions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "transactions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"follow_number" integer NOT NULL,
	"iban" varchar(34) NOT NULL,
	"currency" varchar(5) NOT NULL,
	"amount" numeric(12, 2) NOT NULL,
	"date_transaction" date NOT NULL,
	"balance_after_transaction" numeric(12, 2) NOT NULL,
	"name_other_party" varchar(255),
	"iban_other_party" varchar(34),
	"authorization_code" varchar(255),
	"description" varchar(255),
	"cashback_for_date" date
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "ix_transactions_follow_number_iban" ON "transactions" USING btree ("follow_number","iban");
*/